version: '3'

services:
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: mysqldocker
    networks:
      - mynetwork

  php-apache:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: myphpdocker
    ports:
      - 80:80
    networks:
      - mynetwork

networks:
  mynetwork:
